stages:
  preprocess:
    cmd: python -m fan_control.pipeline.preprocess
    deps:
      - data/raw
      - src/fan_control/pipeline/preprocess.py
    params:
      - preprocess
    outs:
      - data/processed:
          cache: false

  train:
    cmd: python -m fan_control.pipeline.train
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - src/fan_control/pipeline/train.py
      - src/fan_control/models/
    params:
      - model.type
      - model.features
      - model.${model.type}
    outs:
      - out/train/models/${model.type}/
      - out/train/logs
    metrics:
      - out/train/metrics.json

  evaluate:
    cmd: python -m fan_control.pipeline.evaluate
    deps:
      - data/processed/val.csv
      - out/train/models/${model.type}/
      - src/fan_control/pipeline/evaluate.py
      - src/fan_control/models/
    params:
      - model.type
      - evaluate.horizons
    outs:
      - out/evaluate/plots
    metrics:
      - out/evaluate/metrics.json
