stages:
  preprocess:
    cmd: python -m fan_control.pipeline.preprocess
    deps:
      - data/raw
      - src/fan_control/pipeline/preprocess.py
    params:
      - preprocess
    outs:
      - data/processed:
          cache: false

  train:
    cmd: python -m fan_control.pipeline.train
    deps:
      - data/processed
      - src/fan_control/pipeline/train.py
      - src/fan_control/core/train.py
    params:
      - model
    outs:
      - models/thermal_model.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false

  evaluate:
    cmd: python -m fan_control.pipeline.evaluate
    deps:
      - data/processed/val.csv
      - models/thermal_model.pkl
      - src/fan_control/pipeline/evaluate.py
      - src/fan_control/core/train.py
    metrics:
      - metrics/val_metrics.json:
          cache: false

  simulate:
    cmd: python -m fan_control.pipeline.simulate
    deps:
      - models/thermal_model.pkl
      - src/fan_control/pipeline/simulate.py
      - src/fan_control/core/simulator.py
      - src/fan_control/core/train.py
      - src/fan_control/control/optimizer.py
    metrics:
      - metrics/sim_metrics.json:
          cache: false
