stages:
  preprocess:
    cmd: python -m fan_control.pipeline.preprocess
    deps:
      - data/raw
      - src/fan_control/pipeline/preprocess.py
    params:
      - preprocess
    outs:
      - data/processed

  train:
    cmd: python -m fan_control.pipeline.train
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - src/fan_control/pipeline/train.py
      - src/fan_control/models/
    params:
      - model.type
      - model.features
      - model.${model.type}
    outs:
      - out/train/models/${model.type}/
      - out/train/logs
    metrics:
      - out/train/metrics.json

  evaluate:
    cmd: python -m fan_control.pipeline.evaluate
    deps:
      - data/processed/val.csv
      - out/train/models/${model.type}/
      - src/fan_control/pipeline/evaluate.py
      - src/fan_control/models/
    params:
      - model.type
      - evaluate.horizons
    outs:
      - out/evaluate/plots/images
    metrics:
      - out/evaluate/metrics.json
    plots:
      - out/evaluate/plots/predicted_vs_actual.json:
          x: cpu_actual
          y: cpu_predicted
          title: "CPU: Predicted vs Actual"
      - out/evaluate/plots/residuals_cpu.json:
          x: error
          y: density
          title: "CPU Residual Distribution"
      - out/evaluate/plots/residuals_gpu.json:
          x: error
          y: density
          title: "GPU Residual Distribution"
      - out/evaluate/plots/rollout_by_horizon.json:
          x: horizon
          y: cpu_rmse
          title: "Rollout RMSE vs Horizon"
      - out/evaluate/plots/physics_pwm.json:
          x: pwm
          y: cpu_temp
          title: "Temperature vs PWM"
      - out/evaluate/plots/physics_power.json:
          x: power
          y: cpu_temp
          title: "Temperature vs Power"
