# DVC Pipeline Parameters
# This file contains all tunable parameters for the ML pipeline

# Preprocessing parameters
preprocess:
  min_power:
    cpu: 10.0
    gpu: 5.0
  max_temp:
    cpu: 95.0
    gpu: 85.0
  test_size: 0.2

# Model Configuration
model:
  type: physics # physics | pinn | gbr | gp

  # Feature configuration (shared across models)
  features:
    state:
    - T_cpu
    - T_gpu
    control:
    - pwm2
    - pwm4
    - pwm5
    disturbance:
    - P_cpu
    - P_gpu
    - T_amb
    targets:
    - T_cpu
    - T_gpu
  physics:
    dt: 1.0 # Time step (seconds)
    # Hybrid v8: Use fitted values from best models (v4 CPU simple + v6 GPU temp-dep)
    # Fitted values: C_cpu=100, G_cpu_base=1.858, C_gpu=65, G_gpu_base=0.8, G_gpu_T=0.196
    C_cpu: 100.0 # CPU thermal capacitance (J/K)
    C_gpu: 65.0 # GPU thermal capacitance (J/K)
    G_cpu_base: 1.86 # CPU base thermal conductance (W/K) - from fitted
    G_cpu_T: 0.0 # CPU: NO temperature dependence (fixed at 0)
    T_ref_cpu: 60.0 # CPU reference temperature (°C)
    G_gpu_base: 0.8 # GPU base thermal conductance at T_ref (W/K) - from fitted
    G_gpu_T: 0.196 # GPU temperature-dependent term (W/K²) - from fitted
    T_ref_gpu: 30.0 # GPU reference temperature (°C)
    # PWM effects from fitted values
    G_cpu_pwm2: 0.1 # CPU cooling from pwm2
    G_cpu_pwm4: 0.1 # CPU cooling from pwm4
    G_cpu_pwm5: 0.1 # CPU cooling from pwm5
    G_gpu_pwm2: 0.0 # GPU cooling from pwm2
    G_gpu_pwm4: 0.1 # GPU cooling from pwm4
    G_gpu_pwm5: 0.1 # GPU cooling from pwm5

  # PINN model parameters (Physics-Informed Neural Network)
  pinn:
    hidden_dims:
    - 64
    - 32
    epochs: 200
    learning_rate: 0.001
    batch_size: 64
    physics_weight: 0.1
    dt: 1.0

  # GBR model parameters (Gradient Boosting Regressor)
  gbr:
    n_estimators: 100
    max_depth: 4
    learning_rate: 0.1
    l2_regularization: 1.0
    random_state: 42

  # GP model parameters (Gaussian Process)
  gp:
    training_iter: 200
    learning_rate: 0.05
    max_train_samples: 3000 # GP is O(n^3), subsample if needed

# Evaluation Configuration
evaluate:
  horizons: # Multi-step rollout horizons to test
    # Optimizer Configuration
  - 10
  - 20
  - 50
optimizer:
  method: COBYLA
  options:
    maxiter: 200
    rhobeg: 15.0
    tol: 0.5

# Controller Configuration
controller:
  targets:
    T_cpu: 83.0
    T_gpu: 60.0
  interval: 2.0
