# DVC Pipeline Parameters
# This file contains all tunable parameters for the ML pipeline

# Preprocessing parameters
preprocess:
  min_power:
    cpu: 10.0
    gpu: 5.0
  max_temp:
    cpu: 95.0
    gpu: 85.0
  test_size: 0.2

# Model Configuration
model:
  type: gp      # physics | pinn | gbr | gp

  # Feature configuration (shared across models)
  features:
    state:
    - T_cpu
    - T_gpu
    control:
    - pwm2
    - pwm4
    - pwm5
    disturbance:
    - P_cpu
    - P_gpu
    - T_amb
    targets:
    - T_cpu
    - T_gpu
  physics:
    dt: 1.0  # Time step (seconds)
    # Initial parameter guesses (will be optimized during training)
    C_cpu: 100.0      # CPU thermal capacitance (J/째C)
    C_gpu: 80.0       # GPU thermal capacitance (J/째C)
    G_cpu_base: 1.0   # CPU base thermal conductance (W/째C)
    G_gpu_base: 0.8   # GPU base thermal conductance (W/째C)
    G_cpu_pwm2: 0.05  # CPU cooling from pwm2
    G_cpu_pwm4: 0.02  # CPU cooling from pwm4
    G_cpu_pwm5: 0.02  # CPU cooling from pwm5
    G_gpu_pwm2: 0.01  # GPU cooling from pwm2
    G_gpu_pwm4: 0.03  # GPU cooling from pwm4
    G_gpu_pwm5: 0.04  # GPU cooling from pwm5

  # PINN model parameters (Physics-Informed Neural Network)
  pinn:
    hidden_dims:
    - 64
    - 32
    epochs: 200
    learning_rate: 0.001
    batch_size: 64
    physics_weight: 0.1
    dt: 1.0

  # GBR model parameters (Gradient Boosting Regressor)
  gbr:
    n_estimators: 100
    max_depth: 4
    learning_rate: 0.1
    l2_regularization: 1.0
    random_state: 42

  # GP model parameters (Gaussian Process)
  gp:
    training_iter: 100
    learning_rate: 0.1
    max_train_samples: 2000  # GP is O(n^3), subsample if needed

# Evaluation Configuration
evaluate:
  horizons:               # Multi-step rollout horizons to test

# Optimizer Configuration
  - 10
  - 20
  - 50
optimizer:
  method: COBYLA
  options:
    maxiter: 200
    rhobeg: 15.0
    tol: 0.5

# Controller Configuration
controller:
  targets:
    T_cpu: 83.0
    T_gpu: 60.0
  interval: 2.0
